require: rubocop-rspec

AllCops:
  NewCops: enable

Style/EmptyLiteral:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Layout/LineLength:
  Max: 150
  Include:
    - 'spec/**/*'

RSpec/EmptyExampleGroup:
  Enabled: false

# Because of the way that blocks are used in RSpecs can end up being long when
# example groups are nested or many examples are checked.
# A similar pattern exists in the DSL for gemspec files.
Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

RSpec/ExpectInHook:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: false

# NOTE: The rspec-tabular commands get confused with the default syntax is used
# for Hashes, so disabling this check for specs so that `Hash[]` can be used.
Style/HashConversion:
  Exclude:
    - 'spec/**/*'
